export const DEFAULT_THEME = {
  '--bg-main':            '#0a0a0a',
  '--bg-secondary':       '#1a1a1a',
  '--text-primary':       '#f5d56a',
  '--text-secondary':     '#999999',
  '--stat-value':         '#e0e0e0',
  '--border-primary':     '#d4a637',
  '--border-light':       '#333333',
  '--input-bg':           '#1a3a2a',
  '--input-border':       '#22c55e',
  '--input-text':         '#86efac',
  '--output-bg':          '#3a1a1a',
  '--output-border':      '#ef4444',
  '--output-text':        '#fca5a5',
  '--node-bg':            '#1a1a1a',
  '--node-border':        '#d4a637',
  '--tier-1-color':       '#888888',
  '--tier-2-color':       '#4ade80',
  '--tier-3-color':       '#60a5fa',
  '--tier-4-color':       '#c084fc',
  '--tier-5-color':       '#fbbf24',
}